services:

  gateway:
    image: nginx:alpine
    container_name: siber8-gateway
    ports:
    - "8080:80"
    volumes:
    - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
    - siber8-network

  yonif:
    image: nginx:alpine
    container_name: siber8-yonif
    volumes:
      - ./yonif:/usr/share/nginx/html:ro
    ports:
      - "8081:80"
    networks:
      - siber8-network

  cyber:
    image: nginx:alpine
    container_name: siber8-cyber
    volumes:
      - ./cyber:/usr/share/nginx/html:ro
    ports:
      - "8082:80"
    networks:
      - siber8-network

  intelijen:
    image: nginx:alpine
    container_name: siber8-intelijen
    volumes:
      - ./intelijen:/usr/share/nginx/html:ro
    ports:
      - "8083:80"
    networks:
      - siber8-network

  postgres:
    image: postgres:18-alpine
    container_name: siber8-postgres
    environment:
      POSTGRES_USER: siber8
      POSTGRES_PASSWORD: siber8_dev_password
      POSTGRES_DB: siber8
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - siber8-network

networks:
  siber8-network:
    driver: bridge

volumes:
  postgres_data:
