"""create personel table

Revision ID: 5ecdaa09b208
Revises: 1de129540223
Create Date: 2026-09-09 22:56:23.579724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ecdaa09b208'
down_revision: Union[str, Sequence[str], None] = '1de129540223'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personel',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nrp', sa.String(length=30), nullable=False),
    sa.Column('nama', sa.String(length=150), nullable=False),
    sa.Column('pangkat', sa.String(length=50), nullable=True),
    sa.Column('korps', sa.String(length=50), nullable=True),
    sa.Column('jabatan', sa.String(length=150), nullable=True),
    sa.Column('kompi', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personel_nrp'), 'personel', ['nrp'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_personel_nrp'), table_name='personel')
    op.drop_table('personel')
    # ### end Alembic commands ###
